<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Name' => 'Имя',

    'Forum Name' => 'Название форума',
    'Category' => 'Категория',
    'Description' => 'Описание',
    'Sort Order' => 'Порядок сортировки',
    
    // Validation messages
    'Title cannot be blank.' => 'Название не может быть пустым.',
    'Category cannot be blank.' => 'Категория должна быть выбрана.',

    // Topic Attribute labels
    'Topic Title' => 'Название темы',
    'Forum' => 'Форум',
    'Author' => 'Автор',
    'Content' => 'Содержание',
    'Status' => 'Статус',
    'Views' => 'Просмотры',
    'Pinned' => 'Закреплено',
    'Locked' => 'Закрыто',
    
    // Status options
    'Active' => 'Активно',
    'Closed' => 'Закрыто',
    'Deleted' => 'Удалено',
    
    // Validation messages
    'Title cannot be blank.' => 'Название темы не может быть пустым.',
    'Content cannot be blank.' => 'Содержание темы не может быть пустым.',
    'Forum cannot be blank.' => 'Форум должен быть выбран.',
];
